<nav class="navbar navbar-inverse  navbar-fixed-top">

	<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">

			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="bs-example-navbar-collapse-1">

				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>

			</button>

			<a class="navbar-brand" href="index.php">Economics</a>

		</div>

<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav">

				<li><a href="aziz.php" class="<?php echo ($active == 'Aziz' ? "active" : "");?>">Zubair Aziz</a></li>
				<li><a href="ostriker.php" class="<?php echo ($active == 'Ostriker' ? "active" : "");?>">Oliver Ostriker</a></li>
				<li><a href="yang.php" class="<?php echo ($active == 'Yang' ? "active" : "");?>">Jimmy Yang</a></li>

			</ul>

		</div>
		
	</div>

</nav>
